### ISSUE TITLE
Dictionnary replace when not in `tag` ?

### ISSUE THREAD

**Issue by Hadrien-DELAITRE** [MrSwitch/esi#4]
Why are you replacing string when it's not a `tag` :
https://github.com/MrSwitch/esi/blob/master/src/esi.js#L70

In my htmlString, I have other script containing such characters as :
`function _callee$(_context) {`.
They are replaced by : `function _callee {`.

Obviously when my page is served client side, javascript fails.

**Comment by MrSwitch** [comment]
If you want to remove that. Check the test script is successful. Then create a PR.
Thanks

**Comment by MrSwitch** [comment]
Thanks, just released `npm i esi@* --save-dev`
